import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Download, Search, Layers, FlaskConical, BookOpen } from 'lucide-react';
import './style.css';

const initial = { price:80, cost:45, tonnes:4000, capex:1000, years:20, discount:10, delay:2 };
const fields = [['price','NdPr price','USD / kg',0,1000],['cost','Operating cost','USD / kg',0,1000],['tonnes','Annual output','tonnes',1,100000],['capex','Initial capital','USD million',0,100000],['years','Operating life','years',1,60],['discount','Discount rate','%',0,50],['delay','Additional delay','years',0,20]];
const fmt = n => Number(n).toLocaleString('en-US', {maximumFractionDigits:1});
async function request(url, options) { const r=await fetch(url,options); if(!r.ok) throw Error('Request failed. Check your inputs and try again.'); return r.json(); }
function App(){
 const [data,setData]=useState(null), [error,setError]=useState(''), [tab,setTab]=useState('Projects'), [query,setQuery]=useState(''), [stage,setStage]=useState('All stages'), [active,setActive]=useState('mountain-pass'), [selected,setSelected]=useState([]), [inputs,setInputs]=useState(initial), [result,setResult]=useState(null), [calculated,setCalculated]=useState(null), [busy,setBusy]=useState(false);
 useEffect(()=>{request('/api/projects').then(setData).catch(e=>setError(e.message));},[]);
 async function calculate(e){e?.preventDefault();setBusy(true);setError('');try{const r=await request('/api/scenario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(inputs)});setResult(r);setCalculated({...inputs});}catch(e){setError(e.message);}finally{setBusy(false);}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({exported_at:new Date().toISOString(),evidence:data,hypothetical_scenario:calculated,result},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='element-research-pack.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const projects=data?.projects||[], p=projects.find(x=>x.id===active), visible=projects.filter(x=>(stage==='All stages'||x.stage===stage)&&`${x.name} ${x.company} ${x.country} ${x.materials.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const stale=result&&JSON.stringify(inputs)!==JSON.stringify(calculated);
 return <><header><a className="brand" href="/">Element <span>Critical minerals research</span></a><nav aria-label="Main navigation">{[['Projects',Layers],['Scenario lab',FlaskConical],['Sources',BookOpen]].map(([t,Icon])=><button key={t} aria-current={tab===t?'page':undefined} className={tab===t?'nav-active':''} onClick={()=>setTab(t)}><Icon size={16}/>{t}</button>)}</nav><button className="export" disabled={!data} onClick={download}><Download size={16}/><span>Export evidence</span></button></header>
 <main><div className="workspace-heading"><div><span className="breadcrumb">Research / Rare earths</span><h1>Rare earth project tracker</h1></div><div className="review-date">Last source review<br/><strong>{data?.checked||'Loading…'}</strong></div></div><div className="status"><span>{projects.length} projects</span><span>United States & Australia</span><span>Manually reviewed issuer data · No live prices</span></div>
 {error&&<div role="alert" className="error">{error} <button onClick={()=>location.reload()}>Reload</button></div>}
 {tab==='Projects'&&<section><div className="section-title"><div><h2>Projects</h2><p>Select a project to review its source data and research notes.</p></div><span className="badge">Nd · Pr · Dy · Tb</span></div><div className="toolbar"><label className="search"><Search size={18}/><input aria-label="Search projects" placeholder="Search project, company or element" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter by stage" value={stage} onChange={e=>setStage(e.target.value)}>{['All stages','Operating','Development','Construction'].map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="desk"><div className="project-list"><div className="table-wrap"><table className="project-table"><thead><tr><th scope="col"><span className="sr-only">Compare</span></th><th scope="col">Project / company</th><th scope="col">Stage</th><th scope="col">NdPr volume</th></tr></thead><tbody>{visible.map(x=><tr key={x.id} className={active===x.id?'chosen':''}><td><input type="checkbox" aria-label={`Compare ${x.name}`} checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?[...selected,x.id]:selected.filter(id=>id!==x.id))}/></td><th scope="row"><button className="project-name" aria-pressed={active===x.id} onClick={()=>setActive(x.id)}>{x.name}</button><span className="table-sub">{x.company} · {x.ticker}</span><span className="table-sub">{x.country}</span></th><td><span className={`stage ${x.stage.toLowerCase()}`}>{x.stage}</span></td><td className="numeric"><strong>{x.volume?fmt(x.volume):'—'}</strong><span className="table-sub">{x.volume?x.unit:'Not captured'}</span><span className="table-sub">{x.basis}</span></td></tr>)}</tbody></table></div>{!data&&<p className="table-note">Loading issuer records…</p>}{data&&!visible.length&&<p className="table-note">No matching projects.</p>}<p className="table-note">Volumes use different reporting bases. Actual output and planned annual capacity are not directly comparable.</p><p className="table-note">Use the checkboxes to compare project records.</p></div>
 {p&&<article className="evidence"><div className="row"><span className="eyebrow">PROJECT DETAILS</span><span className="badge">{p.chain}</span></div><h2>{p.name}</h2><div className="chips">{p.materials.map(m=><span key={m}>{m}</span>)}</div><h4>Reported information</h4><p className="fact">{p.fact}</p><div className="source-meta">{p.period}<br/>Published: {p.published||'Undated webpage'} · Reviewed {data.checked}</div><a className="source-link" href={p.source} target="_blank" rel="noreferrer">Open issuer source <ArrowUpRight size={16}/></a><div className="editorial"><span className="eyebrow">Research notes · Editorial</span><p>{p.view}</p><strong>Follow-up question</strong><p>{p.question}</p></div><h4>Data gaps</h4><ul>{p.gaps.map(g=><li key={g}>{g}</li>)}</ul></article>}</div>
 {selected.length>0&&<div className="comparison"><h3>Comparison <span>{selected.length} selected</span></h3><p>Actual output and planned capacity are not equivalent. Figures are not added together.</p><div className="table-wrap"><table><thead><tr><th>Project</th><th>Value / unit</th><th>Basis</th><th>Period</th><th>Value chain</th></tr></thead><tbody>{projects.filter(x=>selected.includes(x.id)).map(x=><tr key={x.id}><th>{x.name}</th><td>{x.volume?`${fmt(x.volume)} ${x.unit}`:'Not captured'}</td><td>{x.basis}</td><td>{x.period}</td><td>{x.chain}</td></tr>)}</tbody></table></div></div>}</section>}
 {tab==='Scenario lab'&&<section><div className="section-title"><div><h2>Scenario analysis</h2><p>A hypothetical project. Not a forecast or a valuation of any tracked company.</p></div><span className="badge">USD · Pre-tax · Unlevered</span></div><div className="scenario"><form onSubmit={calculate}><h3>Model inputs</h3><p>Illustrative defaults, not issuer guidance.</p><div className="fields">{fields.map(([key,label,unit,min,max])=><label key={key}>{label}<span>{unit}</span><input required type="number" min={min} max={max} step={['years','delay'].includes(key)?1:'any'} value={inputs[key]} onChange={e=>setInputs({...inputs,[key]:e.target.value===''?'':Number(e.target.value)})}/></label>)}</div><button className="primary" disabled={busy}>{busy?'Calculating…':'Calculate scenario'} <ArrowUpRight size={17}/></button></form><div className="scenario-result" aria-live="polite">{!result?<div className="empty"><FlaskConical size={36}/><h3>No scenario calculated</h3><p>Adjust the inputs, then calculate to see how price and timing change the economics.</p></div>:<><span className="eyebrow">ILLUSTRATIVE NET PRESENT VALUE {stale?'· INPUTS CHANGED — RECALCULATE':''}</span><div className={`npv ${result.npv_musd<0?'negative':''}`}>${fmt(result.npv_musd)}<span> million</span></div><div className="result-stats"><div><strong>${fmt(result.annual_musd)}m</strong><span>Annual operating cash flow</span></div><div><strong>${fmt(result.breakeven_usd_kg)}/kg</strong><span>Model break-even price</span></div></div><h4>Price sensitivity <span>NPV · USD million</span></h4><div className="bars">{result.sensitivity.map(s=><div className="bar-row" key={s.price}><span>${s.price}/kg</span><div><i className={s.npv<0?'loss':''} style={{width:`${Math.max(1,Math.abs(s.npv)/Math.max(...result.sensitivity.map(v=>Math.abs(v.npv)))*100)}%`}}/></div><strong>{s.npv>0?'+':''}{fmt(s.npv)}</strong></div>)}</div><p className="fine">Bar length represents absolute magnitude; red values are negative. All other calculated assumptions held constant.</p></>}</div></div><div className="method"><h3>Methodology and exclusions</h3><p>Annual cash flow = (price − operating cost) × tonnes × 1,000. Capital is spent at time zero; the first annual cash flow arrives in year 1 + delay. All operating years use constant output and prices.</p><p>Excluded: tax, royalties, sustaining capital, working capital, closure, financing, by-products and ramp-up. A positive result is not an investment recommendation.</p></div></section>}
 {tab==='Sources'&&<section><div className="section-title"><div><h2>Source register</h2><p>Primary issuer sources. Manually curated snapshots—not automatically refreshed.</p></div></div><div className="source-grid">{projects.map(x=><article key={x.id}><span className="eyebrow">{x.name}</span><h3>{x.source_title}</h3><p>Published {x.published||'date unavailable'}<br/>Reviewed {data.checked}</p><a className="source-link" href={x.source} target="_blank" rel="noreferrer">Read original <ArrowUpRight size={16}/></a><hr/><p>{x.fact}</p></article>)}</div><div className="method"><h3>Coverage and limitations</h3><p>Issuer statements are not independent verification. This starter universe is not exhaustive. Missing values stay missing; different production bases are not combined. Editorial observations identify research questions, not buy or sell signals.</p></div></section>}
 <footer><span>element / supply intelligence</span><span>Research prototype · Not investment advice</span></footer></main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
